#include "utility.h"

void bell() { printf("%c", BELL); }

struct DbLsNote dbLs_beep[] = { {DB_LS_C6, DB_LS_1_8,STD_LOUD}, {DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_siren[] = { {DB_LS_C5, DB_LS_1_8,STD_LOUD}, {DB_LS_C4, DB_LS_1_8,STD_LOUD}, {DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_song[] = { {DB_LS_C4, DB_LS_1_8,STD_LOUD}, {DB_LS_D4, DB_LS_1_8,STD_LOUD}, {DB_LS_E4, DB_LS_1_4,STD_LOUD}, {DB_LS_E4, DB_LS_1_8,STD_LOUD}, {DB_LS_G4, DB_LS_1_8,STD_LOUD}, {DB_LS_F4, DB_LS_1_4,STD_LOUD}, {DB_LS_F4, DB_LS_1_8,STD_LOUD}, {DB_LS_A4, DB_LS_1_8,STD_LOUD}, {DB_LS_G4, DB_LS_1_4,STD_LOUD}, {DB_LS_G4, DB_LS_1_8,STD_LOUD}, {DB_LS_F4, DB_LS_1_8,STD_LOUD}, {DB_LS_E4, DB_LS_1_2,STD_LOUD}, {DB_LS_G4, DB_LS_1_4,STD_LOUD}, {DB_LS_G4, DB_LS_1_8,STD_LOUD}, {DB_LS_F4, DB_LS_1_8,STD_LOUD}, {DB_LS_E4, DB_LS_1_4,STD_LOUD}, {DB_LS_E4, DB_LS_1_8,STD_LOUD}, {DB_LS_G4, DB_LS_1_8,STD_LOUD}, {DB_LS_F4, DB_LS_1_4,STD_LOUD}, {DB_LS_F4, DB_LS_1_8,STD_LOUD}, {DB_LS_E4, DB_LS_1_8,STD_LOUD}, {DB_LS_D4, DB_LS_1_4,STD_LOUD}, {DB_LS_G4, DB_LS_1_4,STD_LOUD}, {DB_LS_E4, DB_LS_1_2,STD_LOUD}, {DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_song1[] = { {DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_1,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_1,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_2,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_2,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_1,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_1,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_bigben[] = { {DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_3,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_3,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_3,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_3,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_ryb[] = { {DB_LS_G4,DB_LS_1_3,STD_LOUD},{DB_LS_G4,DB_LS_1_3,STD_LOUD},{DB_LS_G4,DB_LS_1_2,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_3,STD_LOUD},{DB_LS_H4,DB_LS_1_2,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_1,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_2,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_1,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_avdm[] = { {DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_2,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_2,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_2,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_2,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_slpda[] = { {DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_yankee[] = { {DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_kw[] = { {DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_3,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_3,STD_LOUD},{DB_LS_F5,DB_LS_1_2,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_3,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_3,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_3,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_3,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_2,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_3,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_sm[] = { {DB_LS_PAUSE,DB_LS_1_2,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_3,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_F4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_2,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_C6,DB_LS_1_8,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_C6,DB_LS_1_8,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_4,STD_LOUD},{DB_LS_D6,DB_LS_1_4,STD_LOUD},{DB_LS_LAST, 0,STD_LOUD} };
struct DbLsNote dbLs_pm[] = { {DB_LS_H4,DB_LS_1_16,STD_LOUD},{DB_LS_H5,DB_LS_1_16,STD_LOUD},{DB_LS_FS5,DB_LS_1_16,STD_LOUD},{DB_LS_DS5,DB_LS_1_16,STD_LOUD},{DB_LS_H5,DB_LS_1_32,STD_LOUD},{DB_LS_FS5,DB_LS_1_16,STD_LOUD},{DB_LS_DS5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_16,STD_LOUD},{DB_LS_C6,DB_LS_1_16,STD_LOUD},{DB_LS_G6,DB_LS_1_16,STD_LOUD},{DB_LS_E6,DB_LS_1_16,STD_LOUD},{DB_LS_C6,DB_LS_1_32,STD_LOUD},{DB_LS_G6,DB_LS_1_16,STD_LOUD},{DB_LS_E6,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_16,STD_LOUD},{DB_LS_H5,DB_LS_1_16,STD_LOUD},{DB_LS_FS5,DB_LS_1_16,STD_LOUD},{DB_LS_DS5,DB_LS_1_16,STD_LOUD},{DB_LS_H5,DB_LS_1_32,STD_LOUD},{DB_LS_FS5,DB_LS_1_16,STD_LOUD},{DB_LS_DS5,DB_LS_1_8,STD_LOUD},{DB_LS_DS5,DB_LS_1_32,STD_LOUD},{DB_LS_E5,DB_LS_1_32,STD_LOUD},{DB_LS_F5,DB_LS_1_32,STD_LOUD},{DB_LS_F5,DB_LS_1_32,STD_LOUD},{DB_LS_FS5,DB_LS_1_32,STD_LOUD},{DB_LS_G5,DB_LS_1_32,STD_LOUD},{DB_LS_G5,DB_LS_1_32,STD_LOUD},{DB_LS_GS5,DB_LS_1_32,STD_LOUD},{DB_LS_A5,DB_LS_1_16,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_sm2[] = { {DB_LS_E6,DB_LS_1_12,STD_LOUD},{DB_LS_E6,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_E6,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_C6,DB_LS_1_12,STD_LOUD},{DB_LS_E6,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_G6,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_G5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_C6,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_G5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_E5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_A5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_H5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_AS5,DB_LS_1_12,STD_LOUD},{DB_LS_A5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_G5,DB_LS_1_9,STD_LOUD},{DB_LS_E6,DB_LS_1_9,STD_LOUD},{DB_LS_G6,DB_LS_1_9,STD_LOUD},{DB_LS_A6,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_F6,DB_LS_1_12,STD_LOUD},{DB_LS_G6,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_E6,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_C6,DB_LS_1_12,STD_LOUD},{DB_LS_D6,DB_LS_1_12,STD_LOUD},{DB_LS_H5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_C6,DB_LS_1_9,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_9,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_9,STD_LOUD},{DB_LS_G5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_E5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_A5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_H5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_AS5,DB_LS_1_12,STD_LOUD},{DB_LS_A5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_G5,DB_LS_1_12,STD_LOUD},{DB_LS_E6,DB_LS_1_12,STD_LOUD},{DB_LS_G6,DB_LS_1_12,STD_LOUD},{DB_LS_A6,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_F6,DB_LS_1_12,STD_LOUD},{DB_LS_G6,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_E6,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_C6,DB_LS_1_12,STD_LOUD},{DB_LS_D6,DB_LS_1_12,STD_LOUD},{DB_LS_H5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_12,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_sw[] = { {DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_2,STD_LOUD},{DB_LS_C6,DB_LS_1_2,STD_LOUD},{DB_LS_AS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_2,STD_LOUD},{DB_LS_C6,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_2,STD_LOUD},{DB_LS_C6,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_AS5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_2,STD_LOUD},{DB_LS_C6,DB_LS_1_2,STD_LOUD},{DB_LS_AS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_2,STD_LOUD},{DB_LS_C6,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_2,STD_LOUD},{DB_LS_C6,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_AS5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_16,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_AS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_16,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_AS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_C6,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_16,STD_LOUD},{DB_LS_G5,DB_LS_1_2,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_AS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C6,DB_LS_1_8,STD_LOUD},{DB_LS_C6,DB_LS_1_16,STD_LOUD},{DB_LS_F6,DB_LS_1_4,STD_LOUD},{DB_LS_DS6,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_4,STD_LOUD},{DB_LS_C6,DB_LS_1_8,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_GS5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_C6,DB_LS_1_1,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_coffee[] = { {DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_F4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_enter[] = { {DB_LS_D4,DB_LS_1_4,STD_LOUD},{DB_LS_DS4,DB_LS_1_4,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_1,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_DS5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_1,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_take[] = { {DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_GS5,DB_LS_1_8,STD_LOUD},{DB_LS_GS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_GS5,DB_LS_1_8,STD_LOUD},{DB_LS_GS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_GS5,DB_LS_1_8,STD_LOUD},{DB_LS_GS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_car[] = { {DB_LS_E4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_3,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_3,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_3,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_E4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_3,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_3,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_3,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_2,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_2,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_st[] = { {DB_LS_D4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_16,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_16,STD_LOUD},{DB_LS_E4,DB_LS_1_16,STD_LOUD},{DB_LS_A4,DB_LS_1_16,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_tetris[] = { {DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_H4,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_A4,DB_LS_1_2,STD_LOUD},{DB_LS_GS4,DB_LS_1_2,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_H4,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_2,STD_LOUD},{DB_LS_GS5,DB_LS_1_2,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_wicki[] = { {DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_4,STD_LOUD},{DB_LS_E6,DB_LS_1_4,STD_LOUD},{DB_LS_D6,DB_LS_1_8,STD_LOUD},{DB_LS_D6,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_4,STD_LOUD},{DB_LS_E6,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_8,STD_LOUD},{DB_LS_D6,DB_LS_1_4,STD_LOUD},{DB_LS_F6,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_8,STD_LOUD},{DB_LS_G6,DB_LS_1_4,STD_LOUD},{DB_LS_E6,DB_LS_1_4,STD_LOUD},{DB_LS_D6,DB_LS_1_2,STD_LOUD},{DB_LS_G6,DB_LS_1_4,STD_LOUD},{DB_LS_F6,DB_LS_1_4,STD_LOUD},{DB_LS_E6,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_8,STD_LOUD},{DB_LS_C6,DB_LS_1_4,STD_LOUD},{DB_LS_G6,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_4,STD_LOUD},{DB_LS_E6,DB_LS_1_4,STD_LOUD},{DB_LS_F6,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_8,STD_LOUD},{DB_LS_F6,DB_LS_1_8,STD_LOUD},{DB_LS_G6,DB_LS_1_4,STD_LOUD},{DB_LS_E6,DB_LS_1_4,STD_LOUD},{DB_LS_D6,DB_LS_1_2,STD_LOUD},{DB_LS_D6,DB_LS_1_8,STD_LOUD},{DB_LS_D6,DB_LS_1_8,STD_LOUD},{DB_LS_FS6,DB_LS_1_4,STD_LOUD},{DB_LS_D6,DB_LS_1_4,STD_LOUD},{DB_LS_D6,DB_LS_1_8,STD_LOUD},{DB_LS_C6,DB_LS_1_8,STD_LOUD},{DB_LS_C6,DB_LS_1_8,STD_LOUD},{DB_LS_C6,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_8,STD_LOUD},{DB_LS_D6,DB_LS_1_4,STD_LOUD},{DB_LS_G6,DB_LS_1_8,STD_LOUD},{DB_LS_G6,DB_LS_1_2,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_camp[] = { {DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_9,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_2,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_9,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_G4,DB_LS_1_2,STD_LOUD},{DB_LS_A4,DB_LS_1_2,STD_LOUD},{DB_LS_H4,DB_LS_1_3,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_sm3[] = { {DB_LS_C5,DB_LS_1_12,STD_LOUD},{DB_LS_C6,DB_LS_1_12,STD_LOUD},{DB_LS_A4,DB_LS_1_12,STD_LOUD},{DB_LS_A5,DB_LS_1_12,STD_LOUD},{DB_LS_AS4,DB_LS_1_12,STD_LOUD},{DB_LS_AS5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_6,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_C5,DB_LS_1_12,STD_LOUD},{DB_LS_C6,DB_LS_1_12,STD_LOUD},{DB_LS_A4,DB_LS_1_12,STD_LOUD},{DB_LS_A5,DB_LS_1_12,STD_LOUD},{DB_LS_AS4,DB_LS_1_12,STD_LOUD},{DB_LS_AS5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_6,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_F4,DB_LS_1_12,STD_LOUD},{DB_LS_F5,DB_LS_1_12,STD_LOUD},{DB_LS_D4,DB_LS_1_12,STD_LOUD},{DB_LS_D5,DB_LS_1_12,STD_LOUD},{DB_LS_DS4,DB_LS_1_12,STD_LOUD},{DB_LS_DS5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_6,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_F4,DB_LS_1_12,STD_LOUD},{DB_LS_F5,DB_LS_1_12,STD_LOUD},{DB_LS_D4,DB_LS_1_12,STD_LOUD},{DB_LS_D5,DB_LS_1_12,STD_LOUD},{DB_LS_DS4,DB_LS_1_12,STD_LOUD},{DB_LS_DS5,DB_LS_1_12,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_6,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_6,STD_LOUD},{DB_LS_DS5,DB_LS_1_18,STD_LOUD},{DB_LS_CS5,DB_LS_1_18,STD_LOUD},{DB_LS_D5,DB_LS_1_18,STD_LOUD},{DB_LS_CS5,DB_LS_1_6,STD_LOUD},{DB_LS_DS5,DB_LS_1_6,STD_LOUD},{DB_LS_DS5,DB_LS_1_6,STD_LOUD},{DB_LS_GS4,DB_LS_1_6,STD_LOUD},{DB_LS_G4,DB_LS_1_6,STD_LOUD},{DB_LS_CS5,DB_LS_1_6,STD_LOUD},{DB_LS_C5,DB_LS_1_18,STD_LOUD},{DB_LS_FS5,DB_LS_1_18,STD_LOUD},{DB_LS_F5,DB_LS_1_18,STD_LOUD},{DB_LS_E4,DB_LS_1_18,STD_LOUD},{DB_LS_AS5,DB_LS_1_18,STD_LOUD},{DB_LS_A5,DB_LS_1_18,STD_LOUD},{DB_LS_GS5,DB_LS_1_10,STD_LOUD},{DB_LS_DS5,DB_LS_1_10,STD_LOUD},{DB_LS_H4,DB_LS_1_10,STD_LOUD},{DB_LS_AS4,DB_LS_1_10,STD_LOUD},{DB_LS_A4,DB_LS_1_10,STD_LOUD},{DB_LS_GS4,DB_LS_1_10,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_3,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_harry[] = { {DB_LS_PAUSE,DB_LS_1_2,STD_LOUD},{DB_LS_D4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_2,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_A4,DB_LS_1_2,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_F4,DB_LS_1_2,STD_LOUD},{DB_LS_GS4,DB_LS_1_4,STD_LOUD},{DB_LS_D4,DB_LS_1_1,STD_LOUD},{DB_LS_D4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_2,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_2,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_DS5,DB_LS_1_2,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_DS5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_4,STD_LOUD},{DB_LS_CS4,DB_LS_1_2,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_1,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_DS5,DB_LS_1_2,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_CS5,DB_LS_1_2,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_4,STD_LOUD},{DB_LS_CS4,DB_LS_1_2,STD_LOUD},{DB_LS_D4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_1,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_2,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_DS5,DB_LS_1_2,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_DS5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_4,STD_LOUD},{DB_LS_CS4,DB_LS_1_2,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_1,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_sim[] = { {DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_FS5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_2,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_knight[] = { {DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_3,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_3,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_G5,DB_LS_1_2,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_3,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_3,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_32,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_mii[] = { {DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_4,STD_LOUD},{DB_LS_DS6,DB_LS_1_8,STD_LOUD},{DB_LS_D6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_GS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_GS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_DS5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_2,STD_LOUD},{DB_LS_D6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_4,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_D6,DB_LS_1_8,STD_LOUD},{DB_LS_FS6,DB_LS_1_8,STD_LOUD},{DB_LS_A6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_5,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_2,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_2,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_2,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_2,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_CS5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_2,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_CS5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_8,STD_LOUD},{DB_LS_GS5,DB_LS_1_4,STD_LOUD},{DB_LS_DS5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_4,STD_LOUD},{DB_LS_DS5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_1,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_4,STD_LOUD},{DB_LS_DS6,DB_LS_1_8,STD_LOUD},{DB_LS_D6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_GS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_GS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_DS5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_E6,DB_LS_1_2,STD_LOUD},{DB_LS_D6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_4,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_G5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_AS5,DB_LS_1_4,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_D6,DB_LS_1_8,STD_LOUD},{DB_LS_FS6,DB_LS_1_8,STD_LOUD},{DB_LS_A6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_5,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_2,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_2,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_2,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_2,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_CS5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_2,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_CS5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_8,STD_LOUD},{DB_LS_GS5,DB_LS_1_4,STD_LOUD},{DB_LS_DS5,DB_LS_1_8,STD_LOUD},{DB_LS_CS5,DB_LS_1_4,STD_LOUD},{DB_LS_DS5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_1,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_CS6,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS5,DB_LS_1_8,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_cantina[] = { {DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_E4,DB_LS_1_2,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_GS4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_E4,DB_LS_1_2,STD_LOUD},{DB_LS_E4,DB_LS_1_2,STD_LOUD},{DB_LS_G4,DB_LS_1_2,STD_LOUD},{DB_LS_H4,DB_LS_1_2,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_panter[] = { {DB_LS_PAUSE,DB_LS_1_2,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_DS4,DB_LS_1_8,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_DS4,DB_LS_1_8,STD_LOUD},{DB_LS_E4,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_E4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_2,STD_LOUD},{DB_LS_A4,DB_LS_1_16,STD_LOUD},{DB_LS_G4,DB_LS_1_16,STD_LOUD},{DB_LS_E4,DB_LS_1_16,STD_LOUD},{DB_LS_D4,DB_LS_1_16,STD_LOUD},{DB_LS_E4,DB_LS_1_2,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_DS4,DB_LS_1_4,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_DS4,DB_LS_1_8,STD_LOUD},{DB_LS_E4,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_DS5,DB_LS_1_1,STD_LOUD},{DB_LS_D5,DB_LS_1_2,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_DS4,DB_LS_1_8,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_DS4,DB_LS_1_8,STD_LOUD},{DB_LS_E4,DB_LS_1_8,STD_LOUD},{DB_LS_FS4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_C5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_E4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_2,STD_LOUD},{DB_LS_A4,DB_LS_1_16,STD_LOUD},{DB_LS_G4,DB_LS_1_16,STD_LOUD},{DB_LS_E4,DB_LS_1_16,STD_LOUD},{DB_LS_D4,DB_LS_1_16,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_D5,DB_LS_1_8,STD_LOUD},{DB_LS_H4,DB_LS_1_8,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_8,STD_LOUD},{DB_LS_E4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_16,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_16,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_16,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_AS4,DB_LS_1_16,STD_LOUD},{DB_LS_A4,DB_LS_1_8,STD_LOUD},{DB_LS_G4,DB_LS_1_16,STD_LOUD},{DB_LS_E4,DB_LS_1_16,STD_LOUD},{DB_LS_D4,DB_LS_1_16,STD_LOUD},{DB_LS_E4,DB_LS_1_16,STD_LOUD},{DB_LS_E4,DB_LS_1_16,STD_LOUD},{DB_LS_E4,DB_LS_1_2,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_elise[] = { {DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_3,STD_LOUD},{DB_LS_C4,DB_LS_1_4,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_3,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_3,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_3,STD_LOUD},{DB_LS_C4,DB_LS_1_4,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_3,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_3,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_3,STD_LOUD},{DB_LS_C4,DB_LS_1_4,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_3,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_3,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_3,STD_LOUD},{DB_LS_C4,DB_LS_1_4,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_F5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_F4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_3,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_1,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_3,STD_LOUD},{DB_LS_C4,DB_LS_1_4,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_3,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_G4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_3,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_3,STD_LOUD},{DB_LS_C4,DB_LS_1_4,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_3,STD_LOUD},{DB_LS_E4,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_H4,DB_LS_1_4,STD_LOUD},{DB_LS_A4,DB_LS_1_1,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_FF_tokyo[] = { {DB_LS_PAUSE,DB_LS_1_2,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_9,STD_LOUD},{DB_LS_F5,DB_LS_1_9,STD_LOUD},{DB_LS_A5,DB_LS_1_9,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_9,STD_LOUD},{DB_LS_F5,DB_LS_1_9,STD_LOUD},{DB_LS_A5,DB_LS_1_9,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_9,STD_LOUD},{DB_LS_F5,DB_LS_1_9,STD_LOUD},{DB_LS_A5,DB_LS_1_9,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_9,STD_LOUD},{DB_LS_F5,DB_LS_1_9,STD_LOUD},{DB_LS_A5,DB_LS_1_9,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_9,STD_LOUD},{DB_LS_F5,DB_LS_1_9,STD_LOUD},{DB_LS_A5,DB_LS_1_9,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_H5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_D6,DB_LS_1_9,STD_LOUD},{DB_LS_C6,DB_LS_1_9,STD_LOUD},{DB_LS_H5,DB_LS_1_9,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_D6,DB_LS_1_9,STD_LOUD},{DB_LS_C6,DB_LS_1_9,STD_LOUD},{DB_LS_H5,DB_LS_1_9,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_A5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_9,STD_LOUD},{DB_LS_F5,DB_LS_1_9,STD_LOUD},{DB_LS_A5,DB_LS_1_9,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_9,STD_LOUD},{DB_LS_F5,DB_LS_1_9,STD_LOUD},{DB_LS_A5,DB_LS_1_9,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_9,STD_LOUD},{DB_LS_F5,DB_LS_1_9,STD_LOUD},{DB_LS_A5,DB_LS_1_9,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_E5,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_8,STD_LOUD},{DB_LS_PAUSE,DB_LS_1_2,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
//struct DbLsNote dbLs_prince[] = { {DB_LS_DS5,DB_LS_1_4,STD_LOUD},{DB_LS_DS7,DB_LS_1_4,STD_LOUD},{DB_LS_DS5,DB_LS_1_16,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_AS4,DB_LS_1_4,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };
struct DbLsNote dbLs_Birthday[] = { {DB_LS_G5,DB_LS_1_5,STD_LOUD},{DB_LS_G5,DB_LS_1_16,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_C6,DB_LS_1_4,STD_LOUD},{DB_LS_H5,DB_LS_1_2,STD_LOUD},{DB_LS_G5,DB_LS_1_5,STD_LOUD},{DB_LS_G5,DB_LS_1_16,STD_LOUD},{DB_LS_G5,DB_LS_1_4,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_D6,DB_LS_1_4,STD_LOUD},{DB_LS_C6,DB_LS_1_2,STD_LOUD},{DB_LS_G5,DB_LS_1_5,STD_LOUD},{DB_LS_G5,DB_LS_1_16,STD_LOUD},{DB_LS_C6,DB_LS_1_4,STD_LOUD},{DB_LS_E5,DB_LS_1_4,STD_LOUD},{DB_LS_C6,DB_LS_1_5,STD_LOUD},{DB_LS_H5,DB_LS_1_16,STD_LOUD},{DB_LS_A5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_5,STD_LOUD},{DB_LS_E5,DB_LS_1_16,STD_LOUD},{DB_LS_C5,DB_LS_1_4,STD_LOUD},{DB_LS_D5,DB_LS_1_4,STD_LOUD},{DB_LS_C5,DB_LS_1_2,STD_LOUD},{DB_LS_LAST, DB_LS_1_4,STD_LOUD} };





struct DbLsNote* dbLs_ALL[MaxSongs] = {
dbLs_beep,
dbLs_siren,
dbLs_song,
dbLs_song1,
dbLs_bigben,
dbLs_ryb,
dbLs_avdm,
dbLs_slpda,
dbLs_yankee,
dbLs_kw,
dbLs_sm,
dbLs_sm2,
dbLs_sm3,
dbLs_pm,
dbLs_sw,
dbLs_coffee,
dbLs_enter,
dbLs_take,
dbLs_car,
dbLs_st,
dbLs_tetris,
dbLs_wicki,
dbLs_camp,
dbLs_harry,
dbLs_sim,
dbLs_knight,
dbLs_mii,
dbLs_cantina,
dbLs_panter,
dbLs_elise,
dbLs_FF_tokyo,
dbLs_Birthday
};

bool bufEmty() {
	FILE* in = stdin;
	int c;

	if (!(in != NULL && feof(in) && (c = fgetc(in)) != EOF && c != '\n')) {
		return 1;
	}
	else {
		return 0;
	}

}

void readAndDiscardRestOfLine(FILE* in)
{
	int c;
	//while ((c = fgetc(in)) != EOF && c != '\n');
	//while ((c = fgetc(in)) != EOF && c != '\n');
	//printf("Push Enter if programm buggs\n");

	while (in != NULL && feof(in) && (c = fgetc(in)) != EOF && c != '\n');


}

void flush() {
	readAndDiscardRestOfLine(stdin);
}
void flushW() {
	int c = '\n';
	FILE* in = stdin;
	//printf("Push enter!\n");
	waitS(25, 1);
	fputc(' ', in);
	fputc('\n', in);
	c = fgetc(in);

	while ((!waitS(25, 0)) && (in != NULL && c != EOF && c != '\n' && c != '\0' && c != NULL))
	{
		c = fgetc(in);

		//printf(". %i ,\"%i %c\"",!waitS(25,0),c,c);
	}

}

volatile int bret = 1;
void WINAPI Thread()
{
	while (bret)
	{
		if (_getche() == '\r') {
			bret = 1;
			printf(" get rn\n");
			break;
		}
		else {
			printf("no\n");

		}
	}
	return;
}
bool anyKey() {
	if (GetKeyState('\r') < 0) {
		return 1;
	}

	return 0;
}/*
bool anyKey() {
	if (bret) {
		bret = 0;
		printf("set 0\n");

	}
	CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)Thread, NULL, 0, NULL);

	return bret;
}*/
void wait(int tim) {
	clock_t begin;
	int ti = 0;
	begin = clock();
	while ((((clock() - begin) / (CLOCKS_PER_SEC / 1000))) <= tim);
}

bool waitS(int tim, bool start) {
	static clock_t begin;
	if (start)
		begin = clock();

	int ti = 0;
	return	!((((clock() - begin) / (CLOCKS_PER_SEC / 1000))) <= tim);
}
long int sonlen(struct DbLsNote* pNotes) {
	unsigned int i = 0;
	long int x = 0;
	while (pNotes[i].pitch != DB_LS_LAST) {
		x += notLenC[pNotes[i].length];
		i++;
	}
	return x;
}
long int sonlenDB(struct DbLsNote* pNotes) {
	unsigned int i = 0;
	long int x = 0;
	while (pNotes[i].pitch != DB_LS_LAST) {
		x += notLenDB[pNotes[i].length] * 50;
		i++;
	}
	return x;
}
int realLen(uint8_t len) {
	return notLenC[len];
}
void playSong(struct DbLsNote* pNotes) {
	long int lenmax = 0;
	long int lencurr = 0;
	lenmax = sonlen(pNotes);
	printf("The song lasts %0.3lf seconds!\n", (double)lenmax / 1000);
	color(GELBh);
	printf("Press enter to stop!\n");
	rcolor;
	unsigned int i = 0;
	bool end = 0;
	int cwait = 0;
	lenmax = sonlen(pNotes);
	color(VIOLETTh);
	while (pNotes[i].pitch != DB_LS_LAST) {
		printf("Status %0.2lf%% played (remaining time %0.3lf sec)                \r", percent((lenmax), lencurr), (double)(lenmax - lencurr) / 1000);
		if (pNotes[i].pitch != DB_LS_PAUSE) {
			//printf("BEEP: %i\n", pNotes[i].pitch);
			Beep((DWORD)pNotes[i].pitch/* + (DB_LS_C2 - DB_LS_C3)*/, (DWORD)realLen(pNotes[i].length) / 0.7);
			cwait = (realLen(pNotes[i].length) * 2);
			//cwait = 0;
		}
		else {
			//printf("WAIT : %i\n", pNotes[i].length);
			cwait = (realLen(pNotes[i].length));
		}
		waitS(cwait, 1);
		while (!waitS(cwait, 0) && !(end = anyKey()));
		if (end) {
			flush();
			break;
		}
		lencurr += realLen(pNotes[i].length);
		//wait(75);
		i++;
	}
	for (int io = 0; io != 100; io++)
		printf(" ");
	printf("\r");
	if (!end) {
		color(GRUENh);
		printf("Status %0.2lf%% played\n", percent(1, 1));
	}
	else {
		printf("Status %0.2lf%% played - exit\n", percent((lenmax), lencurr));
	}
	rcolor;
}
void color(int Color)
{
	HANDLE handle = GetStdHandle(STD_OUTPUT_HANDLE);
	SetConsoleTextAttribute(handle, Color);
}

double percent(int max, int current) {
	if (max == 0) {
		return 0;
	}
	double x = (double)(current) / (double)max * 100;

	return x;
}
char ynrespond() {
	char c = 0;
	char cr = 0;
	cr = _getch();
	while ((c = GROSS_2_KLEIN(cr)) != 'n' && c != 'y') {
		color(ROTh);
		printf("\r                                                                                                 \r");
		printf("\r'%c' is not a defined value, type 'y' or 'n', try again!", cr);
		cr = _getch();
	}
	printf("\r                                                                                                 \r");
	if (GROSS(cr)) {
		color(GELBh);
		printf("This letter '%c' is a capital letter!\n\tPlease use lowercase letters!\n", cr);
	}
	rcolor;
	return c;
}
int int_inp() {
	char s[300] = "";
	int i = 0;
	bool b = 1;
	while (1) {
		i = 0;
		gets_s(s);
		flush();
		b = 1;

		while (s[i] != '\0' && b) {
			if (ablechint(s[i]) && !(i == 0 && (s[i] == '+' || s[i] == '-')))
			{
				b = 0;
			}
			i++;
		}
		if (b && s[0] != '\0') {
			sscanf(s, "%i", &i);
			return  i;
		}
		color(ROTh);
		if (s[0] != '\0')
			printf("\n\tWrong input!!!\n\tInput has to be a an integer value!!!\n\t\t\"%s\" is not an integer value!!!\nTry again: ", s);
		rcolor;
	}
}
int int_inp(int from, int to) {
	int res = 0;
	if (from == to) {
		printf("%i\n", from);
		return from;
	}
	while ((res = int_inp()) > to || res < from) {
		color(ROTh);
		printf("\n\tType in a number between %i and %i: ", from - 1, to + 1);
		rcolor;
	}
	return res;
}
void str_inp(char* text, int size) {
	*text = NULL;
	while (*text == NULL) {
		gets_s(text, size);
	}
}
void endofP(void);
char str_inp(FILE* f, char* text, int size) {
	int i = 0;
	char c = 0;

	while ((c = getc(f)) != EOF && c != '\n' && i < size && text != NULL) {
		text[i] = c;
		i++;
	}
	if (text == NULL) {
		color(ROTh);
		printf("Error\n");
		rcolor;
		endofP();
		return 0;
	}
	text[i] = '\0';
	if (c == EOF)
		return -1;
	return 1;

}


bool generateDir(const char* name, DIR** dir) {
	char* pname = NULL;
	char* pnameX = NULL;
	char text[101] = "mkdir ";
	pname = (char*)malloc(strlen(name) + 5);
	pnameX = (char*)malloc(strlen(name) + 5);
	if (pname == NULL) {
		color(ROTh);
		printf("No free RAM is available!!!\n");
		rcolor;
		return 0;
	}
	strcpy(pname, "\"");
	strcat(pname, name);
	strcat(pname, "\\");
	strcat(pname, "\"");

	strcpy(pnameX, name);
	strcat(pnameX, "\\");

	if ((*dir = opendir(pnameX)) == NULL) {
		strcat(text, pname);
		system(text);
		if ((*dir = opendir(pnameX)) == NULL) {
			color(ROTh);
			printf("Can't generate \"%s\\\" directory!\n", name);
			rcolor;
			free(pnameX);
			free(pname);
			return 0;
		}
	}
	closedir(*dir);
	if ((*dir = opendir(pnameX)) == NULL) {
		free(pnameX);
		free(pname);
		return 0;
	}
	free(pname);
	free(pnameX);
	return 1;
}
bool generateDir(const char* name) {
	DIR* dir;
	if (!generateDir(name, &dir))
		return 0;
	closedir(dir);
	return 1;
}
bool fileExist(const char* name, FILE* f) {
	if ((f = fopen(name, "r")) == NULL)
		return 0;
	fclose(f);
	if ((f = fopen(name, "a")) == NULL)
		return 0;
	return 1;
}
bool fileExist(const char* name) {
	FILE* f;
	if ((f = fopen(name, "r")) == NULL)
		return 0;
	fclose(f);
	return 1;
}
void printx(char c, int x) {
	for (0; 0 != x; x--)
		printf("%c", c);
}
void printx(char c, const char* x) {
	printx(c, strlen(x));
	printf("\n");
}
void printxCx(char c, const char* x) {
	printx(c, strlen(x));
	printf("\n%s\n", x);
	printx(c, strlen(x));
	printf("\n");
}
void printxCx(char c, const char* x, int c1, int c2, int c3) {
	color(c1);
	printx(c, strlen(x));
	color(c2);
	printf("\n%s\n", x);
	color(c3);
	printx(c, strlen(x));
	printf("\n");
	rcolor;
}


double map(double x, double in_min, double in_max, double out_min, double out_max) {
	double divisor = (in_max - in_min);
	if (divisor == 0) {
		return -1; //AVR returns -1, SAM returns 0
	}
	return (x - in_min) * (out_max - out_min) / divisor + out_min;
}

void percentGraph(double percentx, const char* format, bool colorx, int steps) {
	/*const float percentYellow = 33;
	const float percentRed = 66;

	const int greenLength = 100 * (steps * 100 / percentx) / percentYellow;
	const int yellowLength = 100 * (steps * 100 / percentx) / percentRed;
	const int redLength = (steps * 100 / percentx) - greenLength - yellowLength;

	color(GRUENh);
	for (auto i = 0; i < greenLength; ++i)
	{
		printf("%c", 219);
	}

	color(GELBh);
	for (auto i = 0; i < greenLength; ++i)
	{
		printf("%c", 219);
	}

	color(ROTh);
	for (auto i = 0; i < greenLength; ++i)
	{
		printf("%c", 219);
	}

	color(GRAU);
	for (auto i = 0; i < steps - (steps * 100 / percentx); ++i)
	{
		printf("%c", 219);
	}

	rcolor;
	*/
	rcolor;
	double middle = 35;
	double max = 70;
	int num = steps / (100 / percentx);
	if (num > steps)
		num = steps;
	middle = map(middle, 0, 100, 0, steps);
	if (((int(middle * 10)) % 10) > 4) {
		//	middle++;
	}
	//printf("middle = %03.1lf ",middle);
	max = map(max, 0, 100, 0, steps);
	if (((int(max * 10)) % 10) > 4) {
		//	max++;
	}
	//printf(" max = %03.1lf", max);
	double shadowpercentx = percentx;
	if (percentx > 100)
		percentx = 100;
	if (percentx <= 100) {
		char xC = 219;
		color(GRUENh);

		//printf("num=%3i", num);
		int i = 0;
		for (i = 0; i != num && (i < middle || colorx == 0); i++) {
			printf("%c", 219);
		}
		if (colorx) {
			color(GELBh);
			for (i; i != num && (i < max || colorx == 0); i++) {
				printf("%c", 219);
			}
			rcolor;
			color(ROTh);
			for (i; i != num; i++) {
				printf("%c", 219);
			}
		}
		else {

		}
		color(GRAU);
		for (int xl = 0; (xl != steps - i) && colorx || (xl != steps - num && !colorx); xl++) {
			printf("%c", 219);
		}
	}
	rcolor;
	printf(format, shadowpercentx);
}
//gets_s